### ISSUE TITLE
Add flag-cn.svg

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/es6rocks.github.io#18]
We need a Chinese flag in svg format to add to `src/templates/default/resources/images/flag-cn.svg` in the `src` branch.

**Comment by UltCombo** [comment]
Since the new layout was implemented, the flags are no longer svg, but rather [png sprites](https://github.com/es6rocks/es6rocks.github.io/blob/src/src/templates/2.0/resources/img/icons.png).

@jaydson shouldn't these sprites be generated automatically? Or just edited manually?

**Comment by UltCombo** [comment]
Also, the Brazilian flag looks faded (the png sprite has like 50% opacity) while the English flag is fully opaque. We should fix this as well.

**Comment by UltCombo** [comment]
So, basically, we need a 24x15 px black and white Chinese flag in png format.
It doesn't seem easy to have 5 stars inside a 24x15 px image while keeping the flag aspect ratio.
Does anyone know someone who can handle this? Maybe a pixel art artist?

@jaydson perhaps we could drop the flags' black and white filter? That would make things easier I believe.

On another topic, @hacke2 how do write "Read in Chinese" in Chinese? That will be the Chinese flag's tooltip. Can you translate "Read in Chinese" to Chinese and post here? Thanks.

**Comment by hacke2** [comment]
@UltCombo “使用中文阅读”

**Comment by UltCombo** [comment]
@hacke2 thanks!

Now we are only missing the flag. Then we should be able launch the Chinese version, right @jaydson ?

**Comment by atilafassina** [comment]
@UltCombo just seen all the rest of this thread now, sorry!
I thought that with the new layout this issue would be pointless, so I didn't worry.

Even now the icons for the flags are not those svg ones we had before.
Maybe Italo would be able to help with new flags.

If not, we can get it from from [the noun project](http://thenounproject.com/).
But then I think we would have to change the png ones that are live now.

**Comment by UltCombo** [comment]
@atilafassina no problem. :smile: 
The noun project flags look good to me. Up to you to decide what's better. `;)`

**Comment by atilafassina** [comment]
sorry taking so long to answer, @UltCombo 

But I think @italowaxman should have a saying here.
So we put one in accordance to the others and what he had in mind while drawing.

**Comment by UltCombo** [comment]
No problem, @atilafassina. This is an open source project so you shouldn't feel forced, please contribute at your own pace without guilt. :wink: 

Still, I'd like to give this a high priority so that we can finally release the Chinese version of ES6Rocks.com with all of @hacke2's translation work.

**Comment by italowaxman** [comment]
@UltCombo you need a chinese SVG flag to incorporate a chinese translate at project, right? I designed the layout but the front-end isn't mine. Another thing too, I'm really into redo all the html / css using some framework already implementing the responsive and using all images in SVG, what do you think @jaydson ?

**Comment by UltCombo** [comment]
@italowaxman the current flags in the site are png, but I guess it doesn't matter much whether you design them in svg or png (svg is better, of course).

**Comment by jaydson** [comment]
@italowaxman let's try to land this chinese version with somethin simpler.
Can you help us with this chinise flag?
After that we can go forward changing whatever we want :)

**Comment by italowaxman** [comment]
@jaydson @UltCombo Here are all the flags to the site in PNG format in the requested format. Anything else?

![english](https://cloud.githubusercontent.com/assets/2953435/6012856/62afc256-ab34-11e4-80b5-365c3a151da8.png)
![portuguese](https://cloud.githubusercontent.com/assets/2953435/6012855/62b06a6c-ab34-11e4-8c31-ffda3e1893fd.png)
![chinese](https://cloud.githubusercontent.com/assets/2953435/6012857/62ed7858-ab34-11e4-9015-516495324608.png)

**Comment by UltCombo** [comment]
Awesome work @italowaxman !

**Comment by UltCombo** [comment]
Oh damn, I almost forgot about this issue again. @jaydson think we can/should release ES6Rocks' Chinese version this weekend? Or should we hold it off until the rebranding is finished?

**Comment by hacke2** [comment]
chinese version layout is messy,why?

**Comment by UltCombo** [comment]
@hacke2 what do you mean by "messy", exactly? Do you have a screenshot?

**Comment by hacke2** [comment]
![qq 20150228095014](https://cloud.githubusercontent.com/assets/6399899/6424218/3f17e5d0-bf2f-11e4-9f8a-f2b3806ef8ef.png)

**Comment by UltCombo** [comment]
@hacke2 oh, I see. I've already reported that issue here: #44
For the time being, the workaround is to reduce the summary text by placing `<!--more-->` earlier in the article's text.

**Comment by hacke2** [comment]
These are my changes or you modify？

**Comment by UltCombo** [comment]
Oh I just noticed, some of the Chinese articles don't have a `<!--more-->` comment.
@hacke2 please add a `<!--more-->` comment where you see fit. Everything before `<!--more-->` is shown in the index page.

**Comment by hacke2** [comment]
OK

**Comment by italowaxman** [comment]
You need something more related to design for this Chinese version?

**Comment by UltCombo** [comment]
I believe this is everything for now, thanks @italowaxman. :smile: 

The Chinene version's template still reads in English (this is the same problem as the current [PT-BR version](http://es6rocks.com/pt-br/), but I guess template internationalization is not a priority at the moment.

@jaydson can we release the Chinese version now?

**Comment by jaydson** [comment]
I'm back (from my vacation).
For sure we can release the Chinese version @UltCombo.
I confess i'm not fully aware of what we need to do for this.

**Comment by UltCombo** [comment]
Welcome back. :smile: 

> I confess i'm not fully aware of what we need to do for this.

@jaydson I believe we just need to `harmonic build` and push the `public` directory to the master branch, as usual. Or did you mean something else?

So far I've been removing the `cn` language from the builds as to not publish the Chinese version before it was ready, but it should build by default when you run `harmonic build`/`harmonic run`.

**Comment by UltCombo** [comment]
@hacke2 the Chinese version is now up -- http://jsrocks.org/cn/
I'm sorry for being so forgetful, I've been really busy with both real life and the ES6Rocks projects were (and still are) undergoing major changes -- you see, the site's name and domain have already changed. `;)`

**Comment by hacke2** [comment]
oh my god!Thanks!Hope that more jser to participate in Chinese!

**Comment by robsongajunior** [comment]
Wooow, I Will Take a look for correction categories link

**Comment by UltCombo** [comment]
@robsongajunior or we can translate the categories to English for the time being. The other Chinese articles already have tags in English.

**Comment by robsongajunior** [comment]
to translate to EN we doesn't need do nothing, EN is default when language is not found.

**Comment by UltCombo** [comment]
@robsongajunior I meant to use English categories in the Chinese version. Aren't you talking about the Chinese categories?
