### ISSUE TITLE
Update og:description

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/es6rocks.github.io#30]
Currently the og:description meta tag reads "Articles and News about ECMA6: Harmony".

Thing is, "ECMA6" looks a bit erroneous. From my view, ECMA&lt;number> reads as the number of a standard published by [Ecma International](http://www.ecma-international.org/). In this sense, ECMAScript would be [ECMA-262](http://www.ecma-international.org/publications/standards/Ecma-262.htm). Of course, very few people know JS by this nomenclature, hence I'd suggest changing the og:description to the more conventional "ES6" nomenclature.

**Comment by UltCombo** [comment]
This should change as part of the rebranding as well. #49 
The og:description should be version-agnostic, and focus on JS.

**Comment by jaydson** [comment]
:+1:

**Comment by UltCombo** [comment]
fixed in the new theme.
