### ISSUE TITLE
what!!!

### ISSUE THREAD

**Issue by hacke2** [es6rocks/es6rocks.github.io#46]
The article is not updated?

**Comment by UltCombo** [comment]
Looks like this slipped under my radar, my bad.

We were supposed to launch the Chinese version upon fixing #18, but we've been busy and had quite a few high priority issues to tackle so we ended up forgetting about that specific issue.

Feel free to send a PR to add a Chinese flag, and/or continue the discussion in #18. I'll lock this issue to not split the discussion in two threads.
