### ISSUE TITLE
Future and branding

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/es6rocks.github.io#49]
So, with ECMAScript edition 6 being renamed to ECMAScript 2015, some questions naturally arise:

- Should this affect the ES6 Rocks branding?
- And what about future ECMAScript versions?

First off, let's settle the scope of the project. I believe once ES7/2016 is released, we will still be covering the bleeding edge ECMAScript features instead of being stuck to ES6, right? This means certain parts of the site must be changed, such as the current slogan:

> A collaborative website about the ECMAScript sixth edition, a.k.a. ES6.

A more general statement would be more appropriate.

As for the name/domain of the project, things are more tricky. "ES2015" is too new and virtually all content in the web so far refers to it as "ES6". Changing the site name to ES2015 would be a terrible idea as it would then look outdated when ES2016 is out. The best option is to avoid versions entirely in the name. What do you guys think, is this a good idea?

//cc @jaydson @felipenmoura @atilafassina @felipenmoura @jcemer @robsongajunior

**Comment by jaydson** [comment]
I already had thought about it when the name thing came out.
I was thinking about a new site called [ecma.rocks](ecma.rocks), but the domain is already taken.
Maybe we can go forward with [ecmarocks.com](ecmarocks.com) or something like that.
Thanks for pointing this out @UltCombo, let's use this thread to define the project future.

**Comment by UltCombo** [comment]
Nice idea. Only problem is that "ecma" sounds like a contagious skin disease imo (sorry Ecma International).

**Comment by atilafassina** [comment]
Arriving late at the discussion...
If the brand is going to be revitalised, I agree it should be version-agnostic.
Although, I agree with @UltCombo, the ECMA isn't very nice to the ears.

I think the new brand should relate directly with "**javascript**". After all, that's what it's all about.
I tried some domain combinations at GoDaddy, and the best one I found (and I actually think it's a good one is **jsrocks.today**. Offers the "current" vibe we're going for, keeps the "rock" mood and resitrict/expand the scope of the blog to anything related to JS.

**Comment by UltCombo** [comment]
> I think the new brand should relate directly with "**javascript**". After all, that's what it's all about.
I tried some domain combinations at GoDaddy, and the best one I found (and I actually think it's a good one is **jsrocks.today**. Offers the "current" vibe we're going for, keeps the "rock" mood and resitrict/expand the scope of the blog to anything related to JS.

Nice! :+1: 

The ".today" TLD is perfect for a blog about the current and latest JS trends, sounds perfect for the site. :smile:

**Comment by jaydson** [comment]
I don't get it.
ECMA looks like Eczema? Is that?
Good or not, ECMA is the spec name.

The problem of using JavaScript™ is that JavaScript™ is a trademark from Oracle :fearful: :imp: 
Yeah yeah, i know that is a lot of websites using "JavaScript", but i don't want to have any kind of issues like that.

The TLD ".today" is cool, but i dont think it will fit with the current and latest JS trends.
For me, ".today" is something new, right? And we already have "old articles", so "today" is not semantic.

Let's keep searching and discussing, i'm pretty sure we'll find the perfect name :)

@felipenmoura @leobalter  something to add on the discussion?

**Comment by UltCombo** [comment]
Another issue that has been re-iterated in the [6to5 rebranding thread](https://github.com/6to5/6to5/issues/596) is that many JavaScript developers have no idea what ECMAScript is.

So, "jsrocks" sounds more accessible and clear to me.

> And we already have "old articles", so "today" is not semantic.

They were "new" when they were first posted. The idea of ".today" is that we will have new content on a frequent basis.

**Comment by jaydson** [comment]
> Another issue that has been re-iterated in the 6to5 rebranding thread is that many JavaScript developers have no idea what ECMAScript is.

So, now we have the power to change this if we want.

We have a lot of JavaScript websites out there teaching, well or not, people about JavaScript until now.
ES6Rocks mission were spread the world about JavaScript's new version, back in that day, ECMAScript 6.

But, i'm convinced that we need to find a new brand if we want to embrace the future of JavaScript.
"JSRocks" looks awesome, but i still don't see the TLD ".today" as a best choice.

Here's a list of terms we can use to choose the new brand:
- js (obviously)
- harmony
- es (i still like the idea of using ecma)
- rocks (to keep compatible with what we have now)

**Comment by leobalter** [comment]
JSRocks.technology \o/

2015-02-03 12:51 GMT-05:00 Jaydson Gomes <notifications@github.com>:

**Comment by felipenmoura** [comment]
sorry for getting so late into the discussion!!
I wouldn't like a name like ecma.something.
I also agree that, it might be a good opportunity to use "javascript" or "js" as reference, exactly due to its brand and recognition. I don't see a conference called "BrazilES", for example, attracting many people, while "BrazilJS" immediately reminds us about JS.

JSRocks would be amazingly good!
Notice that jsrocks.net and jsrocks.org are both available ;)

**Comment by jaydson** [comment]
jsrocks.org seems good to me.

**Comment by UltCombo** [comment]
> jsrocks.org seems good to me.

:+1:

**Comment by atilafassina** [comment]
:+1:

**Comment by jaydson** [comment]
So, everybody agrees? I'll buy the domain.

**Comment by felipenmoura** [comment]
me gusta!

**Comment by atilafassina** [comment]
![](http://media.giphy.com/media/L9kwXOK00OJGM/giphy.gif)

**Comment by jaydson** [comment]
Done.
And now what?

- Change the org name on Github or create a new one?
- Change the logo?
- ES6Rocks redirects to JSRocks?
- Change Twitter account name?

**Comment by UltCombo** [comment]
> Change the org name on Github or create a new one?

Rename is okay in my opinion, GitHub will automatically put redirects in place.

> Change the logo?

I guess so, if the designers can help us on that. `=]`

> ES6Rocks redirects to JSRocks?

Yes.

> Change Twitter account name?

Not sure. I vote for keeping the account and just changing the name (that is, keep the current `@` handle but change the display name).

**Comment by dkran** [comment]
Ultcombo, your twitter is hacked btw.

**Comment by UltCombo** [comment]
@dkran how is that so? https://twitter.com/Ult_Combo I don't see anything suspicious.

**Comment by dkran** [comment]
What about jsnext.org or jsnext.com

**Comment by UltCombo** [comment]
@dkran my Twitter account is [@Ult_Combo](https://twitter.com/Ult_Combo). Did you mistake it by [@Ultcombo](https://twitter.com/Ultcombo)? The latter is an impersonator, I've never made such account.

**Comment by dkran** [comment]
@UltCombo https://github.com/es6rocks/es6rocks.github.io/blob/master/2015/01/temporal-dead-zone-tdz-demystified/index.html line 94.  You linked to the wrong account then.

**Comment by UltCombo** [comment]
@dkran oh damn, thanks!

**Comment by dkran** [comment]
no problem man, I was a single mom lookin' to make 6,500 mo from home anyway.

**Comment by UltCombo** [comment]
Hahah. :smile: Fixed by dde2d7e400ba8df872947f8f9358cdc35e1f41ae / 5a948458e86f687fe7a855b62b92074a3428dbb3

**Comment by italowaxman** [comment]
After talking with the @jaydson  and @UltCombo , I learned of the change project name and decided to make the change the logo. I kept the same concept, in a comparative picture of the new logo with the old version.

![captura de tela 2015-03-12 as 21 24 28](https://cloud.githubusercontent.com/assets/2953435/6631074/6299b86a-c8ff-11e4-9a17-29dfbd411df4.png)

**Comment by UltCombo** [comment]
@italowaxman awesome work!
The "J" being larger than the "S" makes the logo more exotic, less generic. Not sure if that's good or bad, @jaydson can have the final say. :smile:

**Comment by UltCombo** [comment]
@italowaxman is it just me, or in your logo design the "J" somehow resembles a [music note](https://www.google.com.br/search?q=music+note&es_sm=93&source=lnms&tbm=isch&sa=X&ei=KzQCVZfkEMiWapnxgaAC&ved=0CAcQ_AUoAQ&biw=1920&bih=979)? Perhaps it is an idea we could investigate.

**Comment by felipenmoura** [comment]
I liked the logo, but I couldn't see a music note there...although I think it might, indeed, be an idea to be checked out.

**Comment by italowaxman** [comment]
Regarding the musical note, I thought of keeping the brand JS Rocks with the initial concept of the ES6 Rocks just changing the name. But the harmonic maybe implement this idea of musical note keeping a little concept of what already exists today. What do you think?

**Comment by UltCombo** [comment]
Yeah, the music note was just a random idea. It is probably better to keep just one of our projects' logos with that concept.

**Comment by italowaxman** [comment]
Which of the two versions of the new logo JS rocks you prefer?

![Uploading Captura de Tela 2015-03-15 às 10.55.13.png . . .]()

**Comment by italowaxman** [comment]
Which of the two versions of the new logo JS rocks you prefer?

![captura de tela 2015-03-15 as 10 55 13](https://cloud.githubusercontent.com/assets/2953435/6656218/c05422da-cb00-11e4-92dd-ba95b4be6c49.png)

**Comment by UltCombo** [comment]
@italowaxman I personally like the second one (right) -- perhaps the "JS" could be just a *tad bit little* less bold?

**Comment by italowaxman** [comment]
How about this?

![captura de tela 2015-03-15 as 11 07 17](https://cloud.githubusercontent.com/assets/2953435/6656251/3827df80-cb02-11e4-9f6d-cdddeff25d6e.png)

**Comment by UltCombo** [comment]
Perfect, IMHO. :smiley: 
Let's wait for the others' feedback.
@jaydson @felipenmoura @atilafassina @jcemer @robsongajunior

**Comment by italowaxman** [comment]
Nice! Awaiting feedback to proceed with the site restructure.

**Comment by italowaxman** [comment]
The new structure of the site is done and @robsongajunior is already implementing the Harmonic.

**Comment by jaydson** [comment]
I missed that.
The last logo looks awesome @italowaxman

**Comment by felipenmoura** [comment]
f*ing awesome :)

**Comment by robsongajunior** [comment]
finished issue?

**Comment by UltCombo** [comment]
@robsongajunior Well, @jaydson and I are still sorting out some details. But I believe we can center the discussion at #57 now.
