### ISSUE TITLE
QA hack night?

### ISSUE THREAD

**Issue by leobalter** [es6rocks/es6rocks.github.io#50]
Can we set a QA hack night so we can sit along via some video streaming to fix some bugs and dev some wanted features? The group involved here is big, even if I'm very absent in the previous 2 months, but that would help us to address some problems in a funny way.

Feb 10th should work for me, how about you?

**Comment by UltCombo** [comment]
Nice idea! :+1: 

I'm just not sure about doing it in weekdays due to the timezone differences...

**Comment by UltCombo** [comment]
Oh wait, @leobalter you're in Rio right? So I guess it is just @atilafassina who is in a different timezone.

**Comment by leobalter** [comment]
I'm in Boston, but a hack night would be easier to me as it is earlier here. Let's see with @atilafassina if we find anything better.

**Comment by UltCombo** [comment]
I usually work from 11am to 8pm UTC (GMT) on weekdays.

**Comment by atilafassina** [comment]
On feb.10 I'm still 3 hours ahead.
So I probably would be able to join for some hours...

My biggest problem would be internet, since I've recently moved,
I'm still on a temporary network setup (pretty shitty, btw).
I'll try my best to do it, but you should count me as a maybe until I'm set with this...

**Comment by leobalter** [comment]
If you want to set this to a weekend, Feb 21st is the next that works for me. There's no need to rush anyway.

**Comment by jaydson** [comment]
February 10 works for me after 8pm UTC (GMT).

**Comment by UltCombo** [comment]
> February 10 works for me after 8pm UTC (GMT).

Works for me too. :+1:

**Comment by atilafassina** [comment]
:ok_hand:  My internet will probably not be good enough by then.
But I'll give it a try!!!

**Comment by felipenmoura** [comment]
Feb, 10th, then?
for me, it's ok.

**Comment by jaydson** [comment]
So, let's do it?

**Comment by UltCombo** [comment]
looks like I'll be 30 mins or so late, as I'll be leaving the company a bit later today.

**Comment by UltCombo** [comment]
Looks like ad hoc chats and conferences work best for us.
