### ISSUE TITLE
Harmonic not building

### ISSUE THREAD

**Issue by richgilbank** [es6rocks/es6rocks.github.io#51]
Not sure whether to leave this here or in the Harmonic repo, but with node 0.11.16 when running `harmonic run`, it's not running the server or compiling the stylus, but crashing out with:
```
child_process: customFds option is deprecated, use stdio instead.
Cleaning up...
Successfully generated public folder
{ [Error: ENOENT, no such file or directory './src/pages/en']
  errno: -2,
  code: 'ENOENT',
  path: './src/pages/en',
  syscall: 'mkdir' }
```
Related: https://github.com/es6rocks/harmonic/issues/91

**Comment by UltCombo** [comment]
es6rocks/harmonic#91 was a simple deprecation warning that never affected the actual code execution.

Are you using Harmonic from npm (v0.0.9) or the installing it from the master branch?
Do you experience this bug with just ES6Rocks or other projects as well?

**Comment by jaydson** [comment]
Besides what @UltCombo asked, can you please try to generate a page before?
```shell
harmonic new_page "foo"
```
And then try to run again.
If it works, we need to investigate what is happening.

**Comment by UltCombo** [comment]
@jaydson judging by the error message, I'd guess @richgilbank's local copy is missing a `src/pages/en` or `src/pages` directory. The weird thing is, [ES6Rocks does not have a src/pages/en directory](https://github.com/es6rocks/es6rocks.github.io/tree/src/src/pages).

The pages i18n hasn't landed on Harmonic yet, right? https://github.com/es6rocks/harmonic/pull/97

**Comment by jaydson** [comment]
Yep, my fault we didn't landed yet #97.

**Comment by UltCombo** [comment]
@jaydson even then, it is weird that @richgilbank's `harmonic build` is looking for a directory that doesn't exist and that hasn't landed on Harmonic yet.

**Comment by jaydson** [comment]
Probably a bug on `0.0.9` npm's version.

**Comment by UltCombo** [comment]
Yeah, that release is 4 months old. @jaydson we can start with the rapid release cycle now if you'd like.

**Comment by jaydson** [comment]
Sure!

**Comment by richgilbank** [comment]
This was happening on the npm release - couldn't run from master because the `dist` folder's not checked in:
```
module.js:338
    throw err;
          ^
Error: Cannot find module '../dist/bin/cli/harmonic'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/harmonic/entry_points/harmonic.js:4:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

On the NPM release, generating pages doesn't work, but doesn't write any error messages (except harmonic#91). Nothing in the filesystem gets generated.

**Comment by UltCombo** [comment]
@richgilbank the `dist` directory is generated when you run `npm install`/`npm link`. See the [contributing guide](https://github.com/es6rocks/harmonic/blob/master/CONTRIBUTING.md#proposing-pull-requests). `=]`

Basically, what you need to run Harmonic off the master branch is:

```
git clone https://github.com/es6rocks/harmonic.git
cd harmonic
npm link
# now you have Harmonic globally installed running off your local repository
```

**Comment by jaydson** [comment]
@richgilbank please let us know if you're stuck in something.

**Comment by UltCombo** [comment]
@jaydson I'm at work atm, if you want to deploy a new release now you can do:

```
npm version patch
npm publish
```

The prepublish script will install the latest 6to5 version, build and run tests before deploying. Guess we can keep releasing patch versions for now and hold off 1.0.0 until we have a relatively stable API, but it is up to you.

**Comment by richgilbank** [comment]
Yeah it's still looking for `src/pages/en` from the looks of it, even from latest master of harmonic and es6rocks:
```
fs.js:751
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'src/pages/en'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:751:18)
    at /Users/richgilbank/Code/harmonic/dist/bin/cli/util.js:239:16
    at Array.forEach (native)
    at newFile (/Users/richgilbank/Code/harmonic/dist/bin/cli/util.js:235:11)
    at Command.<anonymous> (/Users/richgilbank/Code/harmonic/dist/bin/cli/harmonic.js:54:5)
    at Command.<anonymous> (/Users/richgilbank/Code/harmonic/node_modules/commander/index.js:249:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/Users/richgilbank/Code/harmonic/node_modules/commander/index.js:478:12)
    at Command.parse (/Users/richgilbank/Code/harmonic/node_modules/commander/index.js:370:21)
```
Also a nudge on updating the npm package :wink:

**Comment by UltCombo** [comment]
Looks like I've managed to reproduce the issue -- your local copy is most likely missing the `src/pages/` directory. You can create an empty `src/pages/` directory and the Harmonic commands should work again then.

I'd say this is low priority as you're not supposed to delete the `pages` directory, but anyway, I believe we could be slightly more bulletproof by replacing mkdir with mkdirp in these cases. @jaydson we can file this as an Harmonic issue if it sounds good for you.

**Comment by UltCombo** [comment]
> Also a nudge on updating the npm package :wink:

Yes, we are just switching the deploy model to a rapid release process. I just want a substantial new feature to announce the first release in 4 months, then actually switch to rapid releases. For this purpose, I'm working on https://github.com/es6rocks/harmonic/issues/49 and hope to make the new release by the weekend.

**Comment by richgilbank** [comment]
@UltCombo Maybe I'm missing something, but `src/pages` doesn't seem to be in the working tree here: https://github.com/es6rocks/es6rocks.github.io/tree/master/src. Multiple other files seem to be missing as well. Enough to make me thing I'm definitely missing something...

**Comment by UltCombo** [comment]
@richgilbank yes, harmonic commands should be run in the [`src` branch](https://github.com/es6rocks/es6rocks.github.io/tree/src). The master branch contains the generated site, not the sources.

**Comment by richgilbank** [comment]
Ugh, yeah that would do it. Thanks!

**Comment by UltCombo** [comment]
In the past we've considered merging both branches, but for some reason that didn't seem like a good idea (directory name conflicts or something). Perhaps we could rename master -> gh-pages and src -> master to make this less confusing. Or we could make the repository branches structure more clear in the readme. cc @jaydson 
Anyway, I guess this is minor -- the readme's "writing an article" section demonstrates that harmonic commands should run on `src` (or `src`-based) branches.
