### ISSUE TITLE
Looks badly (1024x600)

### ISSUE THREAD

**Issue by Semigradsky** [es6rocks/es6rocks.github.io#52]
In my netbook (1024x600) site looks badly:

![image](https://cloud.githubusercontent.com/assets/1198848/6113431/5a2f00f0-b0a8-11e4-8798-a761faa6af81.png)

![image](https://cloud.githubusercontent.com/assets/1198848/6113434/6694a5de-b0a8-11e4-930d-bafc449f6b3d.png)

![image](https://cloud.githubusercontent.com/assets/1198848/6113439/72022c5c-b0a8-11e4-919e-b248d867fae4.png)

**Comment by jaydson** [comment]
//cc @robsongajunior can you please check this?

Thanks for pointing this @Semigradsky , we definitely need a mobile-friendly website.

**Comment by felipenmoura** [comment]
Yep.
The mobile version of the layout was about to be designed...then we would apply the responsivity and stuff..but I am not sure how far is it.

**Comment by robsongajunior** [comment]
@jaydson I will check this. i'm sorry for a long time without answer

**Comment by Danguilherme** [comment]
Just found ES6 Rocks website from [an awesome article](http://rmurphey.com/blog/2015/03/23/a-baseline-for-front-end-developers-2015/) and couldn't believe it was made by Brazilians and I didn't know it! As I opened it on mobile, the website layout was all messed up (like the picture from the issue), with "hidden" content (like the categories).

As I am trying to improve at web design (aka CSS and HTML), I wondered if I could help to improve the website. So how does contributing work? Is @robsongajunior the only one with rights to edit or maybe I can help in something (website responsiveness), even with his (or others) "supervision"?

**Comment by italowaxman** [comment]
@Danguilherme  @Semigradsky we are already working on a new version that responsiveness and behave well in several resolutions including mobile screens, soon re-launch the project with all fixed it.

**Comment by jaydson** [comment]
You are welcome to help @Danguilherme 
As @italowaxman said, we're working on the new version right now.
@robsongajunior is working on the Harmonic integration, and soon we'll have it live.
Please keep in touch and we'll love your help.
ASAP the new version will be on github in a new branch, so you'll be able to hack.

**Comment by Danguilherme** [comment]
Great! Will be glad to help.

**Comment by robsongajunior** [comment]
Can we close this Issue?
- Broken page will solved at new #JSROCKS

**Comment by UltCombo** [comment]
@robsongajunior I guess we can close this once we publish the new site (hopefully tonight). :smiley:

**Comment by jaydson** [comment]
yay

**Comment by UltCombo** [comment]
Fixed with the new theme. http://jsrocks.org/
Congratz everyone for the awesome work! @italowaxman @robsongajunior @jaydson
